# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_windows
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_windows)
  Game_config = debug_windows
endif
ifeq ($(config),debug_linux)
  Game_config = debug_linux
endif
ifeq ($(config),release_windows)
  Game_config = release_windows
endif
ifeq ($(config),release_linux)
  Game_config = release_linux
endif

PROJECTS := Game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Game:
ifneq (,$(Game_config))
	@echo "==== Building Game ($(Game_config)) ===="
	@${MAKE} --no-print-directory -C Game -f Makefile config=$(Game_config)
endif

clean:
	@${MAKE} --no-print-directory -C Game -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_windows"
	@echo "  debug_linux"
	@echo "  release_windows"
	@echo "  release_linux"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"